### PR TITLE
Build 1.1.0rc1 conda packages

### PR DESCRIPTION
**Pull request by jonmmease**
Not to be merged.  Just for CI to build conda 1.1.0 release candidate conda packages

### CODE REVIEW

**Comment by jonmmease** [comment]
@etpinard I'm still not sure how to get at the Travis artifacts. Could you post a download like for the conda package from Travis?

Once I have that, I was thinking of trying to upload these 1.1.0rc1 packages to the plotly channel.  Then we can get a few people to test them out from there before you make the final 1.1.0 release.

Thanks!

**Comment by etpinard** [comment]
> I'm still not sure how to get at the Travis artifacts

The download link is this:

https://s3.amazonaws.com/image-exporter-travis-artifacts/plotly/orca/448/448.1/conda-osx-64.zip

where that `448` corresponds to Travis build-from-push run number that you can grab from:

[image](https://travis-ci.org/plotly/orca/builds/414461929?utm_source=github_status&utm_medium=notification)

the `.1` corresponds the rebuild number. So if you don't need to rebuild a run from the same push, that number will always be `.1`.

**Comment by jonmmease** [comment]
@etpinard Great thanks for the link and explanation!

Alright if I try uploading the release candidates to the plotly channel? If testing goes well then I'm happy with master becoming 1.1.0.

**Comment by jonmmease** [comment]
Testing complete

**Pull request closed without merging**
