### PR TITLE
bump electron to 4.2.6

### PR DESCRIPTION
**Pull request by antoinerg**
Although most SVG baselines stayed the same, there are slight differences in rendering for the other baselines (most certainly due to switching to a much newer version of Chromium!).

This PR essentially supersedes https://github.com/plotly/orca/pull/125

- [ ] Test that this PR closes https://github.com/plotly/orca/issues/124

### CODE REVIEW

**Comment by etpinard** [comment]
Thanks very much for taking this on @antoinerg !!

- [ ] We should also make sure @plotly/devops tests the new docker build on stage

**Comment by etpinard** [comment]
> * Test that this PR closes #124

cc @jonmmease here

**Comment by scjody** [comment]
> We should also make sure @plotly/devops team tests the new docker build on stage

Normally the developer making the change should be able to test it. `@plotbot deploy bump-electron-4 to imageserver stage` should get your changes onto stage.

If you need us to test this please let us know in detail what needs to be tested. It looks to me like the fix only affects Python users so do you just need a general test that Orca still works?

**Comment by etpinard** [comment]
> Normally the developer making the change should be able to test it.

I agree, this would be ideal. But, as far as I know, there are no docs on how to test things like: CPU/memory usage, startup time and other things that might be of interest for the image server.

**Comment by scjody** [comment]
> I agree, this would be ideal. But, as far as I know, there are no docs on how to test things like: CPU/memory usage, startup time and other things that might be of interest for the image server.

OK, I didn't realize that was what you wanted. Someone from the team can do that this time and write some documentation for next time.

For CPU and memory usage, I suggest we send the set of test images to the Orca staging server and measure what happens. Do you have a good way to do this? Last time I needed to do this I (wrote a tool)[https://github.com/plotly/streambed/issues/9865#issuecomment-363225820], but it needs some work if it's something we want to keep using.

Do you have any specific concerns other than CPU/memory usage and startup time?

**Comment by antoinerg** [comment]
@scjody in the spirit of not wasting your team's time, let's wait before testing: I will try to bump Ubuntu's version as well.

**Comment by tonkolviktor** [comment]
Hello,

i was having troubles with 1.2.1 version of orca on my raspberry pi.

orca tag v3.2.0 did not work as well: i was getting this error: https://github.com/plotly/orca/issues/164
orca tag v3.20 + this PR did not work as well: because of this: https://github.com/electron/electron/issues/16205
orca tag v3.20 + electron 3.1.3 worked (on raspberry)!

**Comment by antoinerg** [comment]
> orca tag v3.20 + electron 3.1.3 worked (on raspberry)!

@tonkolviktor you might be interested to know specifically set the `electron` binary used by Orca by setting the env variable `ELECTRON_PATH`:
https://github.com/plotly/orca/blob/f40962271ce901492513115854cceb45977448eb/bin/orca.js#L5

**Comment by antoinerg** [comment]
Closing in favor of PR https://github.com/plotly/orca/pull/266

**Pull request closed without merging**
