### PR TITLE
Conda package

### PR DESCRIPTION
**Pull request by jonmmease**
Adds conda recipe and updates CI jobs to build conda packages for OSX, Linux, and Windows.

Supersedes https://github.com/plotly/orca/pull/108 due to CI permission issues.

### CODE REVIEW

**Comment by jonmmease** [comment]
@etpinard green here too! Was there anything else you wanted to look over for this one?

**Comment by etpinard** [comment]
@jonmmease have you tested out https://github.com/plotly/orca/pull/113/commits/d6f9c1ecf3ecd51691756da4f8db5fbcbe0d4326 on a linux machine? If not, I can do it no problem

**Comment by jonmmease** [comment]
No I didn't, that's good point.  I should also check whether there's an analogous issue on Windows.

I'll test both using my same Python script and let you know what I find.

**Comment by jonmmease** [comment]
@etpinard I tested in on Ubuntu and it works just like on OS X.  I tested it on Windows 10 and I had to use some different logic from Python to kill the process, but I was able to so there's nothing that needs to change on the Windows side.

Anything else come to mind?

**Comment by etpinard** [comment]
> I tested in on Ubuntu and it works just like on OS X.

Amazing!



> ything else come to mind?

As this PR updates our README with new installation instructions, I'll like to wait until the conda channel thing is sorted out (cc @chriddyp ) before merging this thing and quickly release `v1.1.0` right after.

**Comment by jonmmease** [comment]
I could back-out the README change and put that in a new PR for the 1.1.0 release.  If we bump the version number in that branch we could go ahead and publish the conda packages, and test them from the anaconda channel, before merging it into master.  We could also do the changelog on that branch (I didn't put anything in there for the `--graph-only` option yet).

**Comment by etpinard** [comment]
> I could back-out the README change and put that in a new PR for the 1.1.0 release.

I'd say do whatever is easier for you. If you think having these commits on master now will help your devflow, then revert back the README changes and merge this thing :dancer: 



> If we bump the version number in that branch we could go ahead and publish the conda packages, and test them from the anaconda channel, before merging it into master. We could also do the changelog on that branch (I didn't put anything in there for the --graph-only option yet).

I usually bump the package version on my local copy of `master` and push it (along with the git tags) straight to `origin master`. I update the changelog in a single commit in one go (no need to do during every PR) before the version commit and copy its content to https://github.com/plotly/orca/releases. The complete checklist is [here](https://github.com/plotly/orca/blob/master/CONTRIBUTING.md#checklist) and we essentially use the same one for plotly.js

That said, I'm open to suggestions if you think we could do better.

**Comment by jonmmease** [comment]
Thanks for explaining, that makes sense. I'll go ahead and revert the README change and then merge this, that way I can start building the conda packages I need for plotly.py dev off of master.

Do you want to just pull the README off of this branch when you do the release?

**Comment by etpinard** [comment]
> Do you want to just pull the README off of this branch when you do the release?

Yep. I'll do that. Thanks!

-------

Once you're happy with the state of `master`, I'll release `v1.1.0`.

**Comment by etpinard** [comment]
Brilliant :dancer:

**Pull request merged**
