### PR TITLE
Add orca timeout

### PR DESCRIPTION
**Pull request by joaoalf**
Part of https://github.com/plotly/streambed/issues/11092

- [x] Tested on On-Prem

### CODE REVIEW

**Comment by joaoalf** [comment]
@antoinerg @etpinard I left this PR as a WIP because I want to add more tests but, can you please take a look to see if I'm on the good direction. Thanks!

**Comment by etpinard** [comment]
Looking good so far :ok_hand:

**Comment by joaoalf** [comment]
@etpinard Please review.

**Comment by etpinard** [comment]
Nicely done :dancer: (once `docker-build-and-push` passes :smirk: )

**Pull request merged**
